import os
import sys

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
if BASE_DIR not in sys.path:
    sys.path.insert(0, BASE_DIR)

import pandas as pd
import numpy as np
import joblib
from flask import Flask, request, render_template

# Import our custom Extractive Summarizer
from extractive_summarizer import ExtractiveSummarizer

# ── Load the trained ML Model from the saved pickle file ──
# This file was generated by running the Jupyter notebook
model_path = os.path.join(BASE_DIR, 'email_summary_model.pkl')
try:
    model = joblib.load(model_path)
except Exception as e:
    # Fallback initialization if the model pickle is not generated yet!
    # So the app won't crash initially.
    print(f"Warning: {e}")
    model = ExtractiveSummarizer(top_n_sentences=2)

# ── Create the Flask web application ──
app = Flask(__name__, 
            template_folder=os.path.join(BASE_DIR, 'templates'), 
            static_folder=os.path.join(BASE_DIR, 'static'))


@app.route('/')
def home():
    """
    Home page — shows the input form where users can paste an email.
    """
    return render_template('index.html')


@app.route('/predict', methods=['POST'])
def predict():
    """
    Prediction endpoint — receives the email text and returns the summary.
    """
    input_text = request.form.get("email_text", "")
    new_email = [str(input_text)]
    
    # Make a prediction/summary using our Extractive Summarizer class
    try:
        if input_text.strip() == "":
            summary = "Please provide an email to summarize."
        else:
            summary = model.predict(new_email)[0]
    except Exception as e:
        summary = f"Error summarizing: {str(e)}"
    
    return render_template('index.html', prediction_text=summary, original_text=input_text)


# ── Start the Flask development server ──
if __name__ == "__main__":
    print("=" * 50)
    print("🚀 Starting Email Summarization Web App...")
    print("   Open your browser and go to: http://127.0.0.1:5001")
    print("=" * 50)
    app.run(debug=True, port=5001)
