"""
app.py — Flask Web Application for Sentiment Analysis
========================================================

This file creates a web server that:
1. Loads the trained sentiment model (sentiment_model.pkl)
2. Serves a web page where users can type Amazon Alexa reviews
3. Predicts whether the review is Positive or Negative
4. Displays the result on the web page

HOW TO RUN:
    1. First, train the model by running the Jupyter notebook (sentiment_model_training.ipynb)
    2. Then run: python app.py
    3. Open your browser and go to: http://127.0.0.1:5000

REQUIREMENTS:
    pip install flask scikit-learn spacy joblib
    python -m spacy download en_core_web_sm
"""

# ── Import required libraries ──
import os
import sys

# Ensure the script's directory is in the Python path so local modules import correctly
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
if BASE_DIR not in sys.path:
    sys.path.insert(0, BASE_DIR)

import pandas as pd
import numpy as np
import joblib
from flask import Flask, request, render_template

# Import our custom tokenizer (needed because the model uses it internally)
from custom_tokenizer_function import CustomTokenizer

# ── Load the trained ML Pipeline from the saved pickle file ──
# This file was generated by running the Jupyter notebook
# It contains the complete pipeline: TF-IDF Vectorizer + LinearSVC Classifier
model_path = os.path.join(BASE_DIR, 'sentiment_model.pkl')
model = joblib.load(model_path)

# ── Create the Flask web application ──
# Explicitly set template and static folders relative to the script's origin
app = Flask(__name__, 
            template_folder=os.path.join(BASE_DIR, 'templates'), 
            static_folder=os.path.join(BASE_DIR, 'static'))


@app.route('/')
def home():
    """
    Home page — shows the input form where users can type a review.
    This renders the templates/index.html file.
    """
    return render_template('index.html')


@app.route('/predict', methods=['POST'])
def predict():
    """
    Prediction endpoint — receives a review from the form and returns the sentiment.
    
    How it works:
    1. User types a review in the text box and clicks "Predict Sentiment"
    2. The form sends a POST request to this endpoint
    3. We extract the review text from the form data
    4. The model predicts the sentiment (0 = Negative, 1 = Positive)
    5. We display the result on the same page
    """
    # Get the review text from the form submission
    # request.form.values() returns all values from the HTML form fields
    new_review = [str(x) for x in request.form.values()]
    
    # Make a prediction using our trained pipeline
    # The pipeline automatically: cleans text → TF-IDF → SVM prediction
    prediction = model.predict(new_review)[0]
    
    # Display the result on the webpage
    if prediction == 0:
        return render_template('index.html', prediction_text='Negative 👎')
    else:
        return render_template('index.html', prediction_text='Positive 👍')


# ── Start the Flask development server ──
if __name__ == "__main__":
    print("=" * 50)
    print("🚀 Starting Sentiment Analysis Web App...")
    print("   Open your browser and go to: http://127.0.0.1:5000")
    print("=" * 50)
    app.run(debug=True)
